In [61]:
import numpy as np

In [62]:
#1 D array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [63]:
#2 D array
np.array([(1,2,3),(6,7,9)])

array([[1, 2, 3],
       [6, 7, 9]])

In [64]:
#creating an array from list
num_list=[1,2,3,4,5,6]
np.array(num_list) 

array([1, 2, 3, 4, 5, 6])

In [65]:
print(np.array(num_list))

[1 2 3 4 5 6]


In [66]:
#Identity array
identity_array=np.identity(5)
print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [67]:
#Identity matrix of 1
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
np.eye(4) * 7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [69]:
#Zero array of given size
print(np.zeros(5))
print('\n')
print(np.zeros((5,6)))

[0. 0. 0. 0. 0.]


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [70]:
#Ones array of given size
print(np.ones(1))
print('\n')
np.ones((5,6))


[1.]




array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [71]:
#Range or interval arrray
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [72]:

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
#line space array generating method
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [74]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [75]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [76]:
np.random.rand(4)

array([0.52141507, 0.61311249, 0.87443314, 0.78807711])

In [77]:
np.random.rand(5,50)

array([[7.68481822e-04, 2.68912841e-02, 6.58989534e-01, 2.22251786e-01,
        5.06929625e-01, 4.21862770e-01, 6.31806597e-01, 1.64023854e-01,
        5.34286374e-02, 3.90491480e-02, 4.42061384e-01, 1.87457994e-01,
        1.94700773e-01, 6.86919403e-01, 2.84831104e-01, 1.94554935e-01,
        6.48348898e-01, 9.47570085e-01, 1.47646918e-01, 3.89477579e-01,
        7.85244078e-01, 8.40675512e-01, 9.56408050e-01, 3.99882459e-01,
        5.87182144e-01, 3.39803793e-01, 8.08980031e-01, 8.86476455e-01,
        5.17570613e-02, 2.50345564e-01, 6.21662608e-01, 2.64640751e-01,
        4.56401415e-02, 7.72684024e-01, 3.03676609e-01, 9.96711837e-01,
        8.94341743e-01, 1.09642545e-01, 3.33347776e-01, 2.00748882e-01,
        1.72061290e-01, 6.09085503e-01, 7.62033462e-01, 9.57421900e-01,
        9.78663261e-01, 8.65099006e-01, 1.12972889e-01, 3.62765837e-01,
        5.65217730e-01, 7.50554488e-01],
       [4.13599241e-01, 8.45752672e-01, 1.79731920e-01, 4.84345005e-01,
        6.44952703e-01,

In [78]:
np.random.randint(5,50)

32

In [79]:
np.random.randint(5,50,10)

array([38, 16, 36, 43, 23, 47, 21, 42, 14, 48])

In [80]:
import random
print(random.seed(10))
print(random.randint(5,50))

None
41


## Indexing and slicing an Array

In [81]:
array_1d=np.array([1,2,3,4,5])

In [82]:
array_1d[1]

2

In [83]:
array_1d[2:4]

array([3, 4])

In [84]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [85]:
array_2d[1][1]

5

In [86]:
#slicing
array_2d[1]

array([4, 5, 6])

In [87]:
array_2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
array_2d[:2,0:2]

array([[1, 2],
       [4, 5]])

In [89]:
array_2d[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
array_2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

### Conditional Selection

In [91]:
arr=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [92]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [93]:
arr[arr>6]

array([7, 8, 9])

In [94]:
arr[arr%2==0]

array([2, 4, 6, 8])

In [95]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [96]:
arr[(arr%2!=0)&(arr>3)]

array([5, 7, 9])

In [97]:
arr>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [98]:
arr==5

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

Basic Functions on Array

In [99]:
arr1=np.arange(0,10)
arr2=np.arange(8,18)

In [100]:
arr1+arr2

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [101]:
arr1*arr2

array([  0,   9,  20,  33,  48,  65,  84, 105, 128, 153])

## Universal Function of numpy

In [102]:
print(np.add(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.divide(arr1,arr2))

[ 8 10 12 14 16 18 20 22 24 26]
[  0   9  20  33  48  65  84 105 128 153]
[-8 -8 -8 -8 -8 -8 -8 -8 -8 -8]
[0.         0.11111111 0.2        0.27272727 0.33333333 0.38461538
 0.42857143 0.46666667 0.5        0.52941176]


In [103]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [105]:
np.sin([0,45,90,180])

array([ 0.        ,  0.85090352,  0.89399666, -0.80115264])

In [106]:
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [107]:
np.tan(arr2)

array([  -6.79971146,   -0.45231566,    0.64836083, -225.95084645,
         -0.63585993,    0.46302113,    7.24460662,   -0.8559934 ,
          0.30063224,    3.49391565])

In [108]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [109]:

np.power(arr1, arr2)

array([         0,          1,       1024,     177147,   16777216,
       1220703125, 1054752768, 1622647863,          0, -217042295])

In [110]:
np.greater(arr1, arr2)

array([False, False, False, False, False, False, False, False, False,
       False])

## Basic statistics

In [111]:
arr=np.arange(2,8)
arr

array([2, 3, 4, 5, 6, 7])

In [112]:
np.std(arr)#standard deviation

1.707825127659933

In [113]:
np.std(arr,axis=0)

1.707825127659933

In [114]:
np.var(arr)#variance

2.9166666666666665

In [115]:
np.mean(arr)#mean

4.5

In [116]:
np.median(arr)

4.5

In [117]:
np.min(arr)

2

In [118]:
np.max(arr)

7

In [119]:
arr2=arr.copy()
arr2

array([2, 3, 4, 5, 6, 7])

In [120]:
arr1 = np.arange(0,6)
arr2 = np.arange(6,12)

In [121]:
np.copyto(arr1, arr2)

In [123]:
np.concatenate((arr1,arr2))

array([ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11])

In [127]:
np.concatenate((arr1, arr2.T), axis=0)

array([ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11])

In [128]:
np.concatenate((arr1, arr2), axis=None)

array([ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11])

In [130]:
np.flipud(arr)#Up/down Flip

array([7, 6, 5, 4, 3, 2])

In [131]:
arr=np.array([1,2,2,3,4,5,4,2,2,2,34,5,4,2,2,4,42,3,4])
np.unique(arr)

array([ 1,  2,  3,  4,  5, 34, 42])